# Generated by Django 5.0.6 on 2024-05-09 09:11

import message.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=message.models.PhoneNumberField(max_length=13),
        ),
    ]
